//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAUP_zgrade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("poruka")]

    public partial class poruka
    { 
        [Display(Name = "ID obavijesti")]
        [Key]
        public int idporuka { get; set; }

        [Display(Name = "Tema poruke")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public string temaPoruke { get; set; }

        [Display(Name = "Sadržaj poruke")]
        [DataType(DataType.MultilineText)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public string tijeloPoruke { get; set; }

        [Display(Name = "Datum poruke")]
        [Required(ErrorMessage = "Datum je obavezan podatak")]
        [DataType(DataType.Date)]
        // ako ne napisemo fiksno ovaj format Google Chrome nece dobro prikazati datumsko po
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy.}", ApplyFormatInEditMode = true)]
        public System.DateTime datumPoruke { get; set; }

        [Display(Name = "Pošiljatelj")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public string posiljateljPoruke { get; set; }
    }
}