//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAUP_zgrade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("obavijesti")]
    public partial class poruka
    {
        [Display(Name = "ID obavijesti")]
        [Key]
        public int idporuka { get; set; }

        [Display(Name = "Tema poruke")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public string temaPoruke { get; set; }

        [Display(Name = "Sadržaj poruke")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public string tijeloPoruke { get; set; }

        [Display(Name = "Datum poruke")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public System.DateTime datumPoruke { get; set; }
    }
}
