//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAUP_zgrade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("stanar")]
    public partial class stanar
    {
        [Display(Name = "ID stanara")]
        [Key]
        public int idstanar { get; set; }

        [Display(Name = "Ime")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public string Ime { get; set; }

        [Display(Name = "Prezime")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public string Prezime { get; set; }

        [Display(Name = "OIB")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "{0} treba imati {1} znamenki")]
        public int OIB { get; set; }

        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        [EmailAddress]
        public string email { get; set; }

        [Display(Name = "Broj telefona")]
        public Nullable<int> telefon { get; set; }

        [Display(Name = "Broj mobitela")]
        public Nullable<int> mobitel { get; set; }

        [Display(Name = "Broj zgrade")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "{0} je obavezan podatak")]
        public int zgrada { get; set; }
    }
}
