//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAUP_zgrade.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("stanar")]
    public partial class stanar
    {
        [Key]
        public int idstanar { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int OIB { get; set; }
        public string email { get; set; }
        public Nullable<int> telefon { get; set; }
        public Nullable<int> mobitel { get; set; }
        public int zgrada { get; set; }
    }
}
