-- MySQL Script generated by MySQL Workbench
-- Fri Jul 14 19:05:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Zzgrade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Zzgrade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Zzgrade` DEFAULT CHARACTER SET utf8 ;
USE `Zzgrade` ;

-- -----------------------------------------------------
-- Table `Zzgrade`.`osoba`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`osoba` (
  `idOsoba` INT NOT NULL AUTO_INCREMENT,
  `imeOsoba` VARCHAR(45) NOT NULL,
  `prezimeOsoba` VARCHAR(45) NOT NULL,
  `emailOsoba` VARCHAR(45) NOT NULL,
  `lozinkaOsoba` VARCHAR(45) NOT NULL,
  `statusOsoba` ENUM('stanar', 'upravitelj', 'admin', 'financije', 'odrzavanje', 'predstavnik') NOT NULL,
  `oibOsoba` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idOsoba`),
  UNIQUE INDEX `emailOsoba_UNIQUE` (`emailOsoba` ASC),
  UNIQUE INDEX `idOsoba_UNIQUE` (`idOsoba` ASC),
  UNIQUE INDEX `oibOsoba_UNIQUE` (`oibOsoba` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zzgrade`.`kontakt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`kontakt` (
  `idkontakt` INT NOT NULL AUTO_INCREMENT,
  `telefonKontakt` VARCHAR(12) NULL,
  `gsmKontakt` VARCHAR(14) NULL,
  `osobaIdKontakt` INT NOT NULL,
  PRIMARY KEY (`idkontakt`),
  UNIQUE INDEX `idkontakt_UNIQUE` (`idkontakt` ASC),
  UNIQUE INDEX `telegonKontakt_UNIQUE` (`telefonKontakt` ASC),
  UNIQUE INDEX `gsmKontakt_UNIQUE` (`gsmKontakt` ASC),
  INDEX `fk_kontakt_osoba1_idx` (`osobaIdKontakt` ASC),
  CONSTRAINT `fk_kontakt_osoba1`
    FOREIGN KEY (`osobaIdKontakt`)
    REFERENCES `Zzgrade`.`osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zzgrade`.`zgrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`zgrada` (
  `idZgrada` INT NOT NULL AUTO_INCREMENT,
  `imeZgrade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idZgrada`),
  UNIQUE INDEX `idZgrada_UNIQUE` (`idZgrada` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zzgrade`.`financije`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`financije` (
  `idFinancije` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `zgradeIdFinancije` INT NOT NULL,
  `datumFinancije` DATE NOT NULL,
  `vrijemeFinamcije` TIME NOT NULL,
  `vrijednostFinancije` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`idFinancije`),
  UNIQUE INDEX `zgradeIdFinancije_UNIQUE` (`zgradeIdFinancije` ASC),
  UNIQUE INDEX `idFinancije_UNIQUE` (`idFinancije` ASC),
  CONSTRAINT `zgradeIdFinancije`
    FOREIGN KEY (`zgradeIdFinancije`)
    REFERENCES `Zzgrade`.`zgrada` (`idZgrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zzgrade`.`poruka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`poruka` (
  `idPoruka` INT NOT NULL AUTO_INCREMENT,
  `temaPoruka` TEXT NOT NULL,
  `tjeloPoruka` LONGTEXT NOT NULL,
  PRIMARY KEY (`idPoruka`),
  UNIQUE INDEX `idPoruka_UNIQUE` (`idPoruka` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zzgrade`.`adresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`adresa` (
  `idAdresa` INT NOT NULL AUTO_INCREMENT,
  `adresaAdresa` VARCHAR(55) NOT NULL,
  `osobaIdAdresa` INT NOT NULL,
  `zgradaIdAdresa` INT NOT NULL,
  PRIMARY KEY (`idAdresa`),
  UNIQUE INDEX `idAdresa_UNIQUE` (`idAdresa` ASC),
  INDEX `fk_adresa_osoba1_idx` (`osobaIdAdresa` ASC),
  INDEX `fk_adresa_zgrada1_idx` (`zgradaIdAdresa` ASC),
  CONSTRAINT `fk_adresa_osoba1`
    FOREIGN KEY (`osobaIdAdresa`)
    REFERENCES `Zzgrade`.`osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adresa_zgrada1`
    FOREIGN KEY (`zgradaIdAdresa`)
    REFERENCES `Zzgrade`.`zgrada` (`idZgrada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zzgrade`.`osobaPoruka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`osobaPoruka` (
  `idOsobaPoruka` INT NOT NULL AUTO_INCREMENT,
  `oosobaFromOsobaPoruka` INT NOT NULL,
  `osobaToOsobaPoruka` INT NOT NULL,
  `porukaIdOsobaPoruka` INT NOT NULL,
  PRIMARY KEY (`idOsobaPoruka`),
  UNIQUE INDEX `idosobaPoruka_UNIQUE` (`idOsobaPoruka` ASC),
  INDEX `oosobaFromOsobaPoruka_idx` (`oosobaFromOsobaPoruka` ASC),
  INDEX `oosobaToOsobaPoruka_idx` (`osobaToOsobaPoruka` ASC),
  INDEX `oosobaFromOsobaPoruka_idx1` (`porukaIdOsobaPoruka` ASC),
  CONSTRAINT `oosobaFromOsobaPoruka`
    FOREIGN KEY (`oosobaFromOsobaPoruka`)
    REFERENCES `Zzgrade`.`osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `oosobaToOsobaPoruka`
    FOREIGN KEY (`osobaToOsobaPoruka`)
    REFERENCES `Zzgrade`.`osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `oosobaFromOsobaPoruka`
    FOREIGN KEY (`porukaIdOsobaPoruka`)
    REFERENCES `Zzgrade`.`poruka` (`idPoruka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zzgrade`.`zahtjev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Zzgrade`.`zahtjev` (
  `idZahtjev` INT NOT NULL AUTO_INCREMENT,
  `stanarIdZahtjev` INT NOT NULL,
  `temaZahtjev` VARCHAR(45) NOT NULL,
  `tjeloZahtjev` TEXT NOT NULL,
  `statusZahtjev` ENUM('poslani', 'u obradi', 'rješeni') NOT NULL DEFAULT 'poslani',
  `porukaPoObradiZahtjev` TEXT NOT NULL,
  PRIMARY KEY (`idZahtjev`),
  UNIQUE INDEX `idZahtjevi_UNIQUE` (`idZahtjev` ASC),
  INDEX `stanarIdZahtjevi_idx` (`stanarIdZahtjev` ASC),
  CONSTRAINT `stanarIdZahtjevi`
    FOREIGN KEY (`stanarIdZahtjev`)
    REFERENCES `Zzgrade`.`osoba` (`idOsoba`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '								';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
